### ISSUE TITLE
Major change needed - Database

### ISSUE THREAD

**Issue by mlepyro** [firebywire/User-Issues#24]
Designer should have this functionallity going forward...

1) When you edit a firework, it MUST update both the open show and global database (fireworktypes.xml).  This includes the name, code, or any other detail.  Note if the show and global database is linked by say product code, and product code is changed... it must not allow a duplicate code.

2) When you make a change to a firework name in the autocomplete grid field in the datagrid, it should pop up saying "Do you wish to EDIT or ADD NEW firework?"  If edit, the name is edited AND BOTH the global and show database is changed.  If ADD NEW, then it creates new firework for BOTH global and show database - window pops up asking to fill out NEQ, price etc same window as the Add New Firework displays.

3) When you load an old show, it should check the show database against the current FireworkTypes.XML database.  If any differences in fields (Name, duration, function time, hazard group, price) It should display the differences in a LEFT / RIGHT style comparison view, and ask "THE SHOW FIREWORKS DIFFER TO YOUR GLOBAL DATABASE, DO YOU WISH TO UPDATE THE SHOW DATA?"  If you click YES it updates all fields in the show, if you click NO it ignores and continues as if nothing had ever happened.

**Comment by Optimumfireworks** [comment]
Ideally point 3 would actually have the ability to choose which items it did which action to, so instead of just YES and NO to all, a set of tick boxes choosing CHANGE TO GLOBAL DB or LEAVE THE SAME would allow you to exclude just one if needed (eg it was supposed to be a different pre fire timing in that show or supposed to be the same  pre fire timing the company that designed it had given it rather than yours)

you could auto populate all of them to do one option if you just clicked OK or even have a CHANGE ALL, LEAVE ALL THE SAME and OK buttons
